export { default as ProfileSidebar } from './ProfileSidebar'
export { default as MainProfilePage } from './MainProfilePage'
export { default as MainProfileFavorites } from './favorites/MainProfileFavorites'
export { default as MainProfileOrders } from './orders/MainProfileOrders'
export { default as MainProfileReviews } from './reviews/MainProfileReviews'