export const ERRORS_STR = {
  INVALID_EMAIL: 'Invalid email',
  INVALID_PASSWORD: 'Invalid password',
  INVALID_NAME: 'Invalid name',
  INVALID_SURNAME: 'Invalid surname',
  INVALID_PHONE: 'Invalid phone',
  INVALID_ADDRESS: 'Invalid address',
  INVALID_CITY: 'Invalid city',
  INVALID_ZIP: 'Invalid zip',
  INVALID_COUNTRY: 'Invalid country',
  INVALID_STATE: 'Invalid state',
  INVALID_BIRTHDAY: 'Invalid birthday',
  INVALID_CREDENTIALS: 'Invalid credentials',
  WENT_WRONG: 'Something went wrong',
  TRY_AGAIN: 'Try again',
  WENT_WRONG_TRY_AGAIN: 'Something went wrong, try again',
  NOT_FOUND: 'Not found',
  PAGE_NOT_FOUND: 'Page not found',
  FORM_REQUIRED: 'This field is required',
  FORM_MIN_LENGTH: (c: any) => `This field must be at least ${c} characters long`,
  FORM_MAX_LENGTH: (c: any) => `This field must be less than ${c} characters long`,
  FORM_NUMBER: 'This field must be a number',
  FORM_EMAIL: 'This field must be a valid email',
  FORM__BUSINESS_EMAIL: 'This field must be a valid business email',
  FORM_STRING: 'This field must be a string',
  FORM_DATE: 'This field must be a valid date',
  FORM_MIN: (c: any) => `This field must be greater than ${c}`,
  FORM_MAX: (c: any) => `This field must be less than ${c}`,
  FORM_MIN_DATE: (c: any) => `This field must be greater than ${c}`,
  FORM_MAX_DATE: (c: any) => `This field must be less than ${c}`,
  FORM_PATTERN: 'This field must match the pattern',
  FORM_MATCH: 'This field must match the other field',
  FORM_UNIQUE: 'This field must be unique',
  FORM_INVALID: 'This field is invalid',
  FORM_PASSWORD: "Password must be at least 8 characters long and contain at least one number and one letter",
  FORM_PASSWORD_CONFIRM: "Password confirmation must match password",
  FORM_PASSWORD_MATCH: "Password confirmation must match password",
  FORM_PASSWORD_NEW_MATCH: "New password must not match od password",
  FORM_PHONE: "Phone number must be valid",
}